require 'GD'

im = GD::Image.new_from_png(ARGV[0])

$count = ARGV[1].to_i
$width = ARGV[2].to_i
$height = ARGV[3].to_i
$xstep = ARGV[4].to_i
$ystep = ARGV[5].to_i
$x_ofs = ARGV[6].to_i
$y_ofs = ARGV[7].to_i
$ascend_x = ARGV[8].to_i
$code_points = ARGV[9].split(',')

name=File.basename(ARGV[0], ".png").upcase

puts "// Generated by make_digits.rb from #{ARGV[0]}"
puts "static constexpr int #{name}_COUNT = #{$count};"

idx = ""

puts "static const PROGMEM char #{name}_BITMAP[] = "
(0..($count-1)).each do |i|
	(0..($height-1)).each do |y|
		print "\""
		(0..($width-1)).each do |x|
			print sprintf("\\x%02x", (255-im.red(im.getPixel(i*$xstep + x + $x_ofs, i*$ystep + y + $y_ofs))) .to_i);
		end
		print "\"\n";
	end 
	puts ""
	idx += "{ (const PROGMEM uint8_t *)(#{name}_BITMAP + #{(i * $height * $width)}) , "
	idx += " #{$code_points[i]}, #{$width}, #{$height}, #{$ascend_x} "
	idx += "},\n";
end
puts ";"


puts "static const PROGMEM glyph_t #{name}_array[#{name}_COUNT] = {"
puts idx
puts "};"
puts ""
puts "static const PROGMEM glyph_header_t #{name} = {"
puts "#{name}_array, #{name}_COUNT, #{$height}+1};"
puts ""


