require 'GD'

im = GD::Image.new_from_png(ARGV[0])

$count = ARGV[1].to_i
$width = ARGV[2].to_i
$height = ARGV[3].to_i
$step = ARGV[4].to_i
$x_ofs = ARGV[5].to_i
$y_ofs = ARGV[6].to_i

name=File.basename(ARGV[0], ".png").upcase

puts "// Generated by make_digits.rb from #{ARGV[0]}"
puts "#define #{name}_COUNT #{$count}"
puts "const PROGMEM glyph_t #{name}[#{name}_COUNT] = "

(0..($count-1)).each do |i|
	print "{ #{$width}, #{$height}, 0, 0, {\n"
	
	(0..($height-1)).each do |y|
		(0..($width-1)).each do |x|
			print sprintf("0x%02x,", (255-im.red(im.getPixel(i*$step + x + $x_ofs, y + $y_ofs))) .to_i);
		end
		print "\n";
	end 
	print "} },\n";
end

